# Company Information
company:
  name: "Basic-Audit Security"
  logo_url: "https://raw.githubusercontent.com/Basic-Audit/logo.png"
  website: "https://github.com/Basic-Audit"
  contact_email: "security@basic-audit.com"

# Report Branding
branding:
  primary_color: "#1E40AF"
  secondary_color: "#3B82F6"
  accent_color: "#F59E0B"
  danger_color: "#DC2626"
  warning_color: "#D97706"
  success_color: "#059669"
  info_color: "#3B82F6"
  font_family: "Inter, system-ui, sans-serif"
  
# Report Settings
report:
  title_prefix: "Security Audit Report"
  company_description: >
    Basic-Audit is an open-source security auditing tool designed to help organizations 
    identify and remediate potential vulnerabilities across various security domains including 
    DNS, SSL/TLS, MongoDB, gRPC, and more.
  confidentiality_notice: >
    CONFIDENTIAL: This security audit report contains sensitive information about the 
    target system's security posture. Distribution should be restricted to authorized 
    personnel only. Handle with appropriate security controls.
  report_footer: >
    Generated by Basic-Audit Security Scanner
    For more information visit: https://github.com/Basic-Audit

# Severity Definitions
severity_levels:
  Critical:
    color: "#DC2626"
    description: "Critical severity findings that require immediate attention. These issues present an immediate risk of system compromise."
    icon: "skull"
  High:
    color: "#D97706"
    description: "High severity findings that should be addressed as soon as possible. These issues present significant security risks."
    icon: "exclamation-triangle"
  Medium:
    color: "#F59E0B"
    description: "Medium severity findings that should be addressed in the near term. These issues present moderate security risks."
    icon: "exclamation"
  Low:
    color: "#059669"
    description: "Low severity findings that should be reviewed and addressed. These issues present minor security risks."
    icon: "info"
  Info:
    color: "#3B82F6"
    description: "Informational findings that provide context about the system's security posture."
    icon: "info-circle"

# Report Sections
sections:
  executive_summary:
    enabled: true
    description: "High-level overview of the security assessment findings"
  methodology:
    enabled: true
    description: "Details about the security testing methodology and approach"
  findings:
    enabled: true
    description: "Detailed technical findings from the security assessment"
    subsections:
      - vulnerabilities
      - misconfigurations
      - best_practices
  remediation:
    enabled: true
    description: "Specific recommendations for addressing identified issues"
  risk_analysis:
    enabled: true
    description: "Analysis of security risks and their potential impact"
  appendices:
    enabled: true
    description: "Additional technical details and supporting information"

charts:
  severity_distribution:
    enabled: true
    type: "pie"
    title: "Findings by Severity"
  timeline:
    enabled: true
    type: "line"
    title: "Finding Discovery Timeline"
  risk_score:
    enabled: true
    type: "gauge"
    title: "Overall Risk Score"
  category_distribution:
    enabled: true
    type: "bar"
    title: "Findings by Category"

export_formats:
  - html
  - pdf
  - json
  - csv 